# Generated by Django 4.1.6 on 2023-02-21 10:57

from django.db import migrations, models
import django.db.models.deletion



def init_model_types(apps, schema_editor):
    # Hardcoded to avoid importing pipeline.enums (which triggers heavy ML dependencies)
    # Keep in sync with pipeline.enums.ModelTypeEnum
    from pipeline.models import ModelType
    for label in ['TRANSFORMER', 'XGBOOST']:
        obj = ModelType()
        obj.label = label
        obj.save()
    
def delete_model_types(apps, schema_editor):
    from pipeline.models import ModelType
    ModelType.objects.raw(f"truncate table {ModelType._meta.db_table} cascade")
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_jobstatus_jobtype_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(default='{}')),
                ('metrics', models.TextField(default='{}')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.dataset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.job')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.modeltype')),
            ],
        ),
        migrations.RunPython(code=init_model_types, reverse_code=delete_model_types),
    ]
