version: '2'

services:

    rb_api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rb_api
        ports:
            - '6006:6006'
        volumes:
            - .:/app
    