# Generated by Django 4.1.5 on 2023-01-18 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from services.models import Language

def init_languages(apps, schema_editor):
    from rb import Lang
    for lang in Lang:
        obj = Language()
        obj.label = lang.name
        obj.save()

def delete_languages(apps, schema_editor):
    Language.objects.raw(f"truncate table {Language._meta.db_table} cascade")
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=50)),
                ('num_rows', models.IntegerField()),
                ('num_cols', models.IntegerField()),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(code=init_languages, reverse_code=delete_languages)
    ]
