# Generated by Django 4.1.5 on 2023-01-18 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from services.models import JobStatus, JobType

def init_jobs(apps, schema_editor):
    tasks = ["Pipeline", "CSCL"]
    for task in tasks:
        obj = JobType()
        obj.label = task
        obj.save()
    statuses = ["Pending", "In progress", "Finished", "Error"]
    for status in statuses:
        obj = JobStatus()
        obj.label = status
        obj.save()

def delete_jobs(apps, schema_editor):
    JobType.objects.raw(f"truncate table {JobType._meta.db_table} cascade")
    JobStatus.objects.raw(f"truncate table {JobStatus._meta.db_table} cascade")
    
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_alter_dataset_num_cols_alter_dataset_num_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(default='{}')),
                ('results', models.TextField(default='{}')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.jobstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.jobtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(code=init_jobs, reverse_code=delete_jobs),
    ]