# Generated by Django 4.2.2 on 2023-06-16 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_jobstatus_jobtype_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='elapsed_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
